# Generated by Django 6.0.3 on 2026-03-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='designation_id',
            field=models.CharField(default='DEID001', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
