# Generated by Django 6.0.3 on 2026-03-24 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Dashboard', '0002_designation_designation_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('joining_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('address', models.TextField(verbose_name='')),
                ('primary_name', models.CharField(max_length=100, null=True)),
                ('primary_relation', models.CharField(max_length=50, null=True)),
                ('primary_phone', models.CharField(max_length=15, null=True)),
                ('primary_email', models.EmailField(max_length=254, null=True)),
                ('primary_address', models.TextField(null=True)),
                ('secondary_name', models.CharField(max_length=100, null=True)),
                ('secondary_relation', models.CharField(max_length=50, null=True)),
                ('secondary_phone', models.CharField(max_length=15, null=True)),
                ('secondary_email', models.EmailField(max_length=254, null=True)),
                ('secondary_address', models.TextField(null=True)),
                ('account_holder', models.CharField(max_length=100, null=True)),
                ('account_number', models.CharField(max_length=50, null=True)),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('branch_name', models.CharField(max_length=100, null=True)),
                ('ifsc_code', models.CharField(max_length=20, null=True)),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR_Dashboard.designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
