# Generated by Django 6.0.3 on 2026-03-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Dashboard', '0003_employeeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='joining_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
