# Generated by Django 6.0.3 on 2026-03-25 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Dashboard', '0004_alter_employeeprofile_joining_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='birthday',
        ),
    ]
