# Generated by Django 6.0.3 on 2026-03-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Dashboard', '0005_remove_employeeprofile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
