# Generated by Django 6.0.3 on 2026-03-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Dashboard', '0007_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
