# Generated by Django 6.0.3 on 2026-03-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Dashboard', '0009_holydayslisting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HolydaysListing',
            new_name='HolidaysListing',
        ),
        migrations.RenameField(
            model_name='holidayslisting',
            old_name='holyday_list',
            new_name='holiday_list',
        ),
    ]
