# Generated by Django 6.0.3 on 2026-03-30 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Dashboard', '0010_rename_holydayslisting_holidayslisting_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='clock_in',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='clock_out',
            new_name='check_out',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_Dashboard.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], default='Absent', max_length=10),
        ),
    ]
